// Run from the repository root: node Evaluate-Rules.cjs
// Reproduces the developer-case regression for the message checker and, for labelled cases, the risk-level results.
// Independent results are in evidence/Blind-Evaluation.json; reproduce the current held-out aggregate with:
// node evaluation/score-blind.cjs prototype/engine.js evaluation/blind-v5.json
const fs=require('fs'),path=require('path');const engine=require('./prototype/engine.js');const cases=JSON.parse(fs.readFileSync(path.join(__dirname,'prototype/evaluation-cases.json'),'utf8'));let tp=0,tn=0,fp=0,fn=0,unsupported=0;
const results=cases.map(c=>{const r=engine.analyse(c.text),actual=r.matches.map(x=>x.id),expected=c.expected;const categoryExact=JSON.stringify([...actual].sort())===JSON.stringify([...expected].sort()),coveragePass=!c.coverage||c.coverage===r.coverage;if(c.coverage==='unsupported')unsupported++;else if(expected.length&&actual.length)tp++;else if(expected.length)fn++;else if(actual.length)fp++;else tn++;return {...c,actual,level:r.risk?r.risk.level:null,exact:categoryExact&&coveragePass,coveragePass}});
const pct=(k,n)=>n?+(100*k/n).toFixed(1):null,share=(rows,f)=>({k:rows.filter(f).length,n:rows.length,pct:pct(rows.filter(f).length,rows.length)});
const labelled=results.filter(r=>r.label&&r.level),by=l=>labelled.filter(r=>r.label===l);
const risk=labelled.length?{fraudHigh:share(by('fraud'),r=>r.level==='high'),fraudWarned:share(by('fraud'),r=>r.level!=='none'),suspiciousWarned:share(by('suspicious'),r=>r.level!=='none'),benignHigh:share(by('benign'),r=>r.level==='high'),benignWarned:share(by('benign'),r=>r.level!=='none')}:null;
const version=engine.analyse('version check').version;
const report={dataset:'Developer-authored synthetic regression cases, also used in development (the original 189 plus cases added for model v3 and checkers 3.3 and 3.5). Not independent validation or real-world fraud accuracy; see the Blind-Evaluation records (blind-v3 to v5, v6, v8 and v9) for sealed tests.',version,cases:cases.length,expectationsPassed:results.filter(x=>x.exact).length,supportedCases:cases.length-unsupported,unsupportedCases:unsupported,unsupportedCoveragePassed:results.filter(x=>x.coverage==='unsupported'&&x.coveragePass).length,truePositive:tp,trueNegative:tn,falsePositive:fp,falseNegative:fn,binaryRecall:tp/(tp+fn),binaryPrecision:tp/(tp+fp),supportedExactCategoryCases:results.filter(x=>x.coverage!=='unsupported'&&x.exact).length,riskLevels:risk,model:engine.model?{weights:engine.model.weights,bias:engine.model.bias,thresholds:engine.model.thresholds,floors:(engine.model.floors||[]).map(f=>f.id)}:null,results};
fs.writeFileSync(path.join(__dirname,'evidence/Rule-Evaluation.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify({version,cases:report.cases,expectationsPassed:report.expectationsPassed,truePositive:tp,trueNegative:tn,falseNegative:fn,falsePositive:fp,unsupported,riskLevels:risk&&Object.fromEntries(Object.entries(risk).map(([k,v])=>[k,`${v.k}/${v.n} (${v.pct}%)`]))},null,2));
